### ISSUE TITLE
Functionality to link users to helper documentation

### ISSUE THREAD

**Issue by pradyunsg** [sanitizers/chronographer-github-app#19]
pip's documentation contains a dedicated section describing how the NEWS file fragments should be written.

https://pip.pypa.io/en/latest/development/contributing/#news-entries

Ideally, we'd like to be able to configure Chronographer to link to it.

**Comment by pradyunsg** [comment]
Related: #10

**Comment by webknjaz** [comment]
It'd say it's a duplicate of #10. I was also thinking maybe to teach it `.. include::` things so that you could just point the config to a chunk of md/rst and make it show up right on that page...

**Comment by webknjaz** [comment]
@pradyunsg I can't decide on how/what needs to be exposed in the config. So far, I've sketched this. 
Ideas? Bikeshedding?

```yaml
---

action-hints:
  external-docs-url: https://pip.pypa.io/how-to-changelog
  include-inline-markdown: >
    Check out https://pip.pypa.io/how-to-changelog
  include-inrepo-markdown: how-to-changelog.md  # needs an extra API call
  show: on-failure | always

...
```
